# Generated by Django 5.2.8 on 2026-02-17 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevMinds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='DevMinds.resource'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='DevMinds.resource'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'resource')},
        ),
    ]
